### ISSUE TITLE
libGL.so missing

### ISSUE THREAD

**Issue by AlwinEgger** [rishihahs/heroku-buildpack-libreoffice#10]
As there are still a few that are using this buildpack, someone might have an answer for me.

I tried to integrate it with the cloudfoundry/java-buildpack using the heroku-buildpack-multi. WOrks fine, my Java-App is up and running. Just LibreOffice exits with an error:
`error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory`

Has anyone seen this yet?

**Comment by nathansamson** [comment]
This should not be a problem if you are using the latest version of the buildpack

**Comment by AlwinEgger** [comment]
With a libGL.so.1 symlink, it works fine.
OpenOlitor/heroku-buildpack-libreoffice@fde2f6036b5e1b9a3a0418a92e2567a91dddeb81

Still wondering why this is not happening on other installations.

**Comment by MohamedHegab** [comment]
It still happens to me and I can't fix it

**Comment by ivanbenko** [comment]
just want to mention it happens to me too and @AlwinEgger  solution solved the problem, thanks
